default: &default
  adapter: postgresql
  encoding: unicode

  database: <%= ENV['POSTGRES_DATABASE'] %>
  pool: 5
  username: postgres
  password:
  host: db

development:
  <<: *default

# production:
#   <<: *default
#   database: estudos_login_production
#   username: estudos_login
#   password: <%= ENV['ESTUDOS_LOGIN_DATABASE_PASSWORD'] %>
